//DTO: DATA TRANSFER OBJECT
// oBJETO DE TRANSFERENCIA DE DATOS:
// SIRVE PARA TRANSFORMAR LA INFORMACIÓN QUE TRANSITA DE UN LUGAR A OTRO EN UN PROYECTO DE SOFTWARE
//PROPOSITO:
//-ASEGURAR EL INGRESO DE INFORMACIÓN
//-CORRECTA DESDE EL EXTERIOR(CLIENTE HTTP, APP MOVIL)
//-VALIDAR ESA IJNFORMACION (ATRBUTOS CORRECTOS)
/// TIPOS DE DATO, LOGITUD, TIPO DE ARCHIVO

export class CreateCategoryDto {

    //CONTEXTO: SE EXPOERA QUE DESDE EL CLIENTE LLEGUE EL NNOMBRE DE LA CATEGORUIA UNICAMENTE
    nombre: string;
}
